apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c", "cp -r /cert/apple-developer-merchantid-domain-association /usr/share/nginx/html/.well-known && nginx -g 'daemon off;'"]
---
apiVersion: v1
kind: Service
metadata:
 name: applepay-demo
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: expose-proxyport
  sessionAffinity: None
  type: LoadBalancer
  selector:
    app: nginx
