apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-podidentity-auth
spec:
  podIdentity:
    provider: azure-workload
    identityId: b8f51514-ea5b-4609-9432-fe91a17e74be
---
apiVersion: keda.sh/v1alpha1 
kind: ScaledObject
metadata:
  name: webapp-demo-scaleobject
  namespace: demo-cluster-ns
spec:
  scaleTargetRef:
    name: webapp-demo
  minReplicaCount: 1 #Change to define how many minimum replicas you want
  maxReplicaCount: 4
  triggers:
  - type: azure-app-insights
    metadata:
      query: "requests | summarize sum(itemCount) by name | where  name == 'GET WeatherForecast/Get' | project sum_itemCount"
      threshold: "5"
      timespan: "PT10S"
      queryEndpoint: https://api.applicationinsights.io/v1/apps/a6f01cd6-d26b-4abd-9c60-1927c25203e2/query
    authenticationRef:
      name: trigger-podIdentity-auth