apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: webapp-demo
  namespace: demo-cluster-ns
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp-demo
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: webapp-demo
  service:
    port: 80
  analysis:
    interval: 1m
    threshold: 3
    iterations: 10
    metrics:
      - name: request-success-rate
        threshold: 99
        interval: 30s
      - name: request-duration
        threshold: 500
        interval: 30s
    webhooks:
      - name: load-test
        url: http://flagger-loadtester.test/
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 -H \"Host: host1.domain.ext\" http://135.237.11.204/WeatherForecast"
