apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-demo
  annotations:
    kubernetes.io/ingress.class: ingress-nginx
spec:
  rules:
    http:
      paths:
      - backend:
          serviceName: webapp-demo
          servicePort: 80
        path: /
        pathType: Prefix
