apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  
spec:
  rules:
  - host: host1.domain.ext
    http:
      paths:
      - backend:
          service:
            name: webapp-demo
            port:
              number: 80
        path: /
        pathType: Prefix
