apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-demo
spec:
  selector:
    matchLabels:
      app: webapp-demo
  replicas: 1 
  template: 
    metadata:
      labels:
        app: webapp-demo
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity
      containers:
      - name: webapp-demo
        image: acr358.azurecr.io/webapp-demo:latest        
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: webapp-demo
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: expose-proxyport
  sessionAffinity: None
  type: LoadBalancer
  selector:
    app: webapp-demo
